version: '3'
services:
  flask:
    image: webapp-flask
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-flask
    links:
      - db
    volumes:
      - "./:/app"
  nginx:
    image: webapp-nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask
  db:
    image: mysql:8.0
    ports:
    - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro